# Imports

In [18]:
import os
import csv
import pandas as pd

# Load of data

In [19]:
df_cancelled = pd.read_csv("../Data and descriptions/Case Rigshospitalet - Cancelled operations.csv", sep=';')
df_complete = pd.read_csv("../Data and descriptions/Case Rigshospitalet - Completed operations.csv", sep = ';')

C:\Users\Bruger\AppData\Local\Temp\ipykernel_12356\3600004165.py:2: DtypeWarning: Columns (13,14,21,22,23,24,25,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df_complete = pd.read_csv("../Data and descriptions/Case Rigshospitalet - Completed operations.csv", sep = ';')

In [20]:
# remove columns with staff and resources
df_complete_wo = df_complete.drop(columns=[col for col in df_complete.columns if col.startswith("Ressource")])
df_complete_wo = df_complete_wo.drop(columns=[col for col in df_complete_wo.columns if col.startswith("Staff")])
df_complete_wo.describe()

,Case-ID Anonymous,Patient Alder,Operationsgang ID,Forsinkelse (minutter),Overskredet (minutter)
count,133158.000000,133158.000000,133158.000000,132491.000000,132537.000000
mean,60156.037437,53.788244,40663.550909,20.511642,25.346198
std,34927.061620,24.889920,52262.972747,50.977296,68.894706
min,1.000000,0.000000,618.000000,-3045.000000,-3003.000000
25%,29928.250000,34.000000,622.000000,0.000000,-10.000000
50%,60097.500000,61.000000,625.000000,14.000000,23.000000
75%,90338.750000,74.000000,107621.000000,40.000000,57.000000
max,120868.000000,107.000000,133218.000000,1585.000000,1560.000000

In [21]:
# Make datetime objects
df_complete_wo['Dato'] = pd.to_datetime(df_complete_wo['Dato'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Pt ankommet til hospitalet'] = pd.to_datetime(df_complete_wo['Pt ankommet til hospitalet'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Planlagt stue klargøring start'] = pd.to_datetime(df_complete_wo['Planlagt stue klargøring start'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Stue klargøring start'] = pd.to_datetime(df_complete_wo['Stue klargøring start'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Stue klargjort'] = pd.to_datetime(df_complete_wo['Stue klargjort'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Patient på stuen'] = pd.to_datetime(df_complete_wo['Patient på stuen'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Patient på stuen (Planlagt)'] = pd.to_datetime(df_complete_wo['Patient på stuen (Planlagt)'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Anæstesistart'] = pd.to_datetime(df_complete_wo['Anæstesistart'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Anæstesi melder klar'] = pd.to_datetime(df_complete_wo['Anæstesi melder klar'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Procedure start'] = pd.to_datetime(df_complete_wo['Procedure start'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Procedure slut'] = pd.to_datetime(df_complete_wo['Procedure slut'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Patient klar til afgang'] = pd.to_datetime(df_complete_wo['Patient klar til afgang'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Patient forlader stuen (Planlagt)'] = pd.to_datetime(df_complete_wo['Patient forlader stuen (Planlagt)'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Patient forlader stuen'] = pd.to_datetime(df_complete_wo['Patient forlader stuen'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Stue rengjort (Planlagt)'] = pd.to_datetime(df_complete_wo['Stue rengjort (Planlagt)'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Stue rengøring start'] = pd.to_datetime(df_complete_wo['Stue rengøring start'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Stue rengjort'] = pd.to_datetime(df_complete_wo['Stue rengjort'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['I opvågning'] = pd.to_datetime(df_complete_wo['I opvågning'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Anæstesistop'] = pd.to_datetime(df_complete_wo['Anæstesistop'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Klar til udskrivelse efter opvågning'] = pd.to_datetime(df_complete_wo['Klar til udskrivelse efter opvågning'], format='%Y-%m-%d %H:%M:%S,%f')
df_complete_wo['Patient forlader afdeling'] = pd.to_datetime(df_complete_wo['Patient forlader afdeling'], format='%Y-%m-%d %H:%M:%S,%f')

In [ ]:
df_complete_wo.dtypes

,Case-ID Anonymous,Patient Alder,Speciale,Stue,Operationsgang ID,Akut case (J/N),Dato,Pt ankommet til hospitalet,Planlagt stue klargøring start,Stue klargøring start,...,I opvågning,Anæstesistop,Klar til udskrivelse efter opvågning,Patient forlader afdeling,Forsinkelse (minutter),Overskredet (minutter),Forsinkelsesårsag,Procedure - Tekst & ID,Aktionsdiagnose - Kode & tekst,Aktionsdiagnose - Gruppe
0,28,29,Øre-næse-hals,OPNORD 23.240 (H),107621,Nej,2024-03-07,2024-03-07 10:51:00,2024-03-07 12:05:00,2024-03-07 13:05:00,...,NaT,NaT,NaT,2024-03-07 15:24:00,95.0,36.0,NaN,AURES ALATAE [1070010290],DQ175: Aures alatae,"Medfødte misdannelser i øje, øre, ansigtet og ..."
1,197,60,Plastikkirurgi,OPNORD 13.114 (H),107621,Nej,2024-01-05,2024-01-05 12:44:00,2024-01-05 13:40:00,2024-01-05 13:48:00,...,NaT,NaT,NaT,2024-01-05 15:06:00,8.0,30.0,NaN,"ARKORREKTION, TRUNCUS -LA [1070012770]",DZ421: Kontakt mhp. plastikkirurgisk efterbeha...,Personer i kontakt med sundhedsvæsenet med hen...
2,197,60,Plastikkirurgi,OPNORD 13.114 (H),107621,Nej,2024-01-05,2024-01-05 12:44:00,2024-01-05 13:40:00,2024-01-05 13:48:00,...,NaT,NaT,NaT,2024-01-05 15:06:00,8.0,30.0,NaN,"BRYSTKORREKTION VED ASYMMETRI -LA, LIPOINJEKTI...",DZ421: Kontakt mhp. plastikkirurgisk efterbeha...,Personer i kontakt med sundhedsvæsenet med hen...
3,230,12,Plastikkirurgi,OPNORD 13.110 (H),107621,Nej,2024-01-26,2024-01-26 08:15:00,2024-01-26 08:00:00,2024-01-26 08:16:00,...,NaT,NaT,NaT,2024-01-26 09:08:00,16.0,-3.0,NaN,"ARKORREKTION, HOVED OG HALS LA [1070010676]",DZ429: Kontakt mhp. plastikkirurgisk efterbeha...,Personer i kontakt med sundhedsvæsenet med hen...
4,238,57,Plastikkirurgi,OPNORD 301,107621,Nej,2024-10-01,2024-10-01 12:14:00,2024-10-01 12:45:00,2024-10-01 13:01:00,...,NaT,NaT,NaT,2024-10-01 13:41:00,16.0,1.0,NaN,"EXCISION, BENIGN TUMOR, TRUNCUS -LA [1070010711]",DQ850: Ikke-malign neurofibromatose,Andre medfødte misdannelser
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133153,120283,59,Øjenkirurgi,GLO Ø 46 STUE 07,625,Nej,2025-12-18,2025-12-18 12:09:00,2025-12-18 12:30:00,2025-12-18 13:13:00,...,NaT,NaT,NaT,2025-12-18 13:36:00,47.0,51.0,NaN,FAKO 2 - LA [1070010663],DH259: Aldersbetinget grå stær (>=50 år) UNS,Sygdomme i øjets linse
133154,120284,58,Øjenkirurgi,GLO Ø 46 STUE 07,625,Nej,2025-12-23,2025-12-23 10:50:00,2025-12-23 11:00:00,2025-12-23 11:32:00,...,NaT,NaT,NaT,2025-12-23 11:55:00,35.0,40.0,NaN,FAKO 3 - LA [1070010664],DH259: Aldersbetinget grå stær (>=50 år) UNS,Sygdomme i øjets linse
133155,120291,70,Øjenkirurgi,GLO Ø 36 STUE 05,625,Nej,2025-12-19,2025-12-19 10:39:00,2025-12-19 11:00:00,2025-12-19 11:52:00,...,NaT,NaT,NaT,2025-12-19 12:07:00,52.0,52.0,NaN,FAKO 3 - LA [1070010664],DH259: Aldersbetinget grå stær (>=50 år) UNS,Sygdomme i øjets linse
133156,120337,87,Øjenkirurgi,GLO Ø 36 STUE 05,625,Nej,2025-12-22,2025-12-22 08:17:00,2025-12-22 08:30:00,2025-12-22 09:04:00,...,NaT,NaT,NaT,2025-12-22 09:52:00,42.0,50.0,NaN,FAKO - LA BILATERAL [1070015679],DH259: Aldersbetinget grå stær (>=50 år) UNS,Sygdomme i øjets linse
133157,120370,63,Øjenkirurgi,GLO VB 10,625,Nej,2025-12-19,2025-12-19 09:28:00,2025-12-19 09:45:00,2025-12-19 10:39:00,...,NaT,NaT,NaT,2025-12-19 11:25:00,58.0,70.0,NaN,FAKO - LA BILATERAL [1070015679],DH259: Aldersbetinget grå stær (>=50 år) UNS,Sygdomme i øjets linse

# Clustering

In [23]:
df_complete_wo.head()

,Case-ID Anonymous,Patient Alder,Speciale,Stue,Operationsgang ID,Akut case (J/N),Dato,Pt ankommet til hospitalet,Planlagt stue klargøring start,Stue klargøring start,...,I opvågning,Anæstesistop,Klar til udskrivelse efter opvågning,Patient forlader afdeling,Forsinkelse (minutter),Overskredet (minutter),Forsinkelsesårsag,Procedure - Tekst & ID,Aktionsdiagnose - Kode & tekst,Aktionsdiagnose - Gruppe
0,28,29,Øre-næse-hals,OPNORD 23.240 (H),107621,Nej,2024-03-07,2024-03-07 10:51:00,2024-03-07 12:05:00,2024-03-07 13:05:00,...,NaT,NaT,NaT,2024-03-07 15:24:00,95.0,36.0,NaN,AURES ALATAE [1070010290],DQ175: Aures alatae,"Medfødte misdannelser i øje, øre, ansigtet og ..."
1,197,60,Plastikkirurgi,OPNORD 13.114 (H),107621,Nej,2024-01-05,2024-01-05 12:44:00,2024-01-05 13:40:00,2024-01-05 13:48:00,...,NaT,NaT,NaT,2024-01-05 15:06:00,8.0,30.0,NaN,"ARKORREKTION, TRUNCUS -LA [1070012770]",DZ421: Kontakt mhp. plastikkirurgisk efterbeha...,Personer i kontakt med sundhedsvæsenet med hen...
2,197,60,Plastikkirurgi,OPNORD 13.114 (H),107621,Nej,2024-01-05,2024-01-05 12:44:00,2024-01-05 13:40:00,2024-01-05 13:48:00,...,NaT,NaT,NaT,2024-01-05 15:06:00,8.0,30.0,NaN,"BRYSTKORREKTION VED ASYMMETRI -LA, LIPOINJEKTI...",DZ421: Kontakt mhp. plastikkirurgisk efterbeha...,Personer i kontakt med sundhedsvæsenet med hen...
3,230,12,Plastikkirurgi,OPNORD 13.110 (H),107621,Nej,2024-01-26,2024-01-26 08:15:00,2024-01-26 08:00:00,2024-01-26 08:16:00,...,NaT,NaT,NaT,2024-01-26 09:08:00,16.0,-3.0,NaN,"ARKORREKTION, HOVED OG HALS LA [1070010676]",DZ429: Kontakt mhp. plastikkirurgisk efterbeha...,Personer i kontakt med sundhedsvæsenet med hen...
4,238,57,Plastikkirurgi,OPNORD 301,107621,Nej,2024-10-01,2024-10-01 12:14:00,2024-10-01 12:45:00,2024-10-01 13:01:00,...,NaT,NaT,NaT,2024-10-01 13:41:00,16.0,1.0,NaN,"EXCISION, BENIGN TUMOR, TRUNCUS -LA [1070010711]",DQ850: Ikke-malign neurofibromatose,Andre medfødte misdannelser